### ISSUE TITLE
Allow other OAuth2 Providers and not just Google

### ISSUE THREAD

**Issue by liamoreilly** [eecs-autograder/autograder-server#599]
It would be very useful to allow other logins via other OAuth2 providers e.g., Microsoft Azure. 

There are currently hard coded URIs and logic that involves Google People API.

**Comment by james-perretta** [comment]
Thanks for your request! Adding other authentication options is definitely an area where I'd be grateful for pull requests. That said, I'd be happy to spearhead the refactoring portion of making it possible to use other OAuth2 providers. Here are my initial thoughts on that front:

1. Add an OAUTH2_CALLBACK_CLASSES variable to our Django settings module. This would be a mapping of OAuth2 provider names (e.g. "google" or "azure") to derived classes of `OAuth2CallbackHandler`, which we describe next.
2. Add an `OAuth2CallbackHandler` base class, perhaps to [oauth2callback.py](https://github.com/eecs-autograder/autograder-server/blob/develop/autograder/rest_api/views/oauth2callback.py). Something along these lines:
```python
class OAuth2CallbackHandler:
    def handle_request(self, request):
        user_info = self.load_user_info(request)
        user = User.objects.get_or_create(
            username=user_info['email'], 
            defaults={'first_name': user_info['first_name'], 'last_name': user_info['last_name']}
        )[0]

        token, created = Token.objects.get_or_create(user=user)
        response = HttpResponseRedirect(state['http_referer'])
        response.set_cookie('token', token.key, domain=settings.SITE_DOMAIN)
        return response

    def load_user_info(self, request):
        """
        Loads user information from the OAuth2 provider and returns
        a dictionary of {'email': ..., 'first_name': ..., 'last_name': ...}.
        Derived classes MUST override this method.
        """
        raise NotImplementedError
```
3. Replace the current oauth2_callback view implementation with something like this:
```python
def oauth2_callback(request):
    # We can likely add the provider name to the request URL
    handler = settings.OAUTH2_CALLBACK_CLASSES['<provider name>']()
    return handler.handle_request(request)
```

Next we turn our attention to the [GoogleOauth2](https://github.com/eecs-autograder/autograder-server/blob/develop/autograder/rest_api/auth.py) class that extends Django's `TokenAuthentication` class. I think the best option here would be to modify its `authenticate_header` method so that it returns multiple OAuth2 redirect URLs instead of just the google one. That way, the website can present the user with a choice as to how they want to authenticate and then redirect them appropriately.


Your thoughts on this @liamoreilly? If I were to make a branch with these changes, would you be willing to contribute some Azure-specific code? 

Thanks!

**Comment by Andrew-Chen-Wang** [comment]
@james-perretta You may want to look at Django allauth's social providers functionality. It may smooth the process out (especially since you're still using django.contrib.auth default user model) and make the OAuth adding easier.

Link to docs: https://django-allauth.readthedocs.io/en/latest/providers.html

**Comment by james-perretta** [comment]
Thanks for the tip, @Andrew-Chen-Wang! I'll have to experiment a bit, but that seems promising.

**Comment by liamoreilly** [comment]
@james-perretta Sorry for the delay! - I don't get much free time. I have been playing around with this (Autograder and OAuth). I think I can integrate Microsoft Azure fairly easily - but only thanks to your skeleton code above. 

I think the main question is if this project should roll-its-own classes and system to manage multiple OAuth2 providers (e.g., as you suggest above); or use the Django library as suggested by @Andrew-Chen-Wang.

Unfortunately, I do not know Django at all and only OAuth 2 a bit. If you choose to go the roll-its-own method (as you detail above) then I am pretty confident I can add in the Microsoft Azure part. If you chose the providers library, then I am not sure I have the time to dig into Django (I might do but no promises).

What are your thoughts?

**Comment by james-perretta** [comment]
@liamoreilly I think at this point the simplest thing to do is go with the skeleton code I posted and then add the provider-specific code ourselves. I will create a branch with the skeleton code sometime in the next few days and will post an update here when I do.

@Andrew-Chen-Wang Thank you again for your recommendation. I looked at django-allauth, and it was honestly more cumbersome to customize than I'd like. There are also certain key assumptions that django-allauth makes that don't go together smoothly with some of the design decisions that went into this repo early on, and I'd rather not have to fight django-allauth to save a small amount of code. If this were a new project, or if we wanted to support a large number of OAuth2 providers, then it might be worth it. That said, it may be useful to peek at their source code for the implementation details of some of the providers...

**Comment by james-perretta** [comment]
@liamoreilly I just pushed the first round of changes to the branch [599_oauth_providers](https://github.com/eecs-autograder/autograder-server/tree/599_oauth_providers). Feel free to add your Azure changes and make a PR to that branch. There's a new setting called `OAUTH2_PROVIDER` in [autograder/settings/base.by](https://github.com/eecs-autograder/autograder-server/blob/599_oauth_providers/autograder/settings/base.py#L72) (also settable as an env var) that points to an entry in the `OAUTH2_CALLBACK_CLASSES` added to oauth2callback.py. Change that value to switch providers.

For the time being, I'd like to leave things as "one active oauth2 provider at a time" if possible, as supporting multiple active providers at once requires modifications to the website frontend as well as some additional considerations in this repo (handling multiple sets of provider secrets, for example). Does your use case allow for that?

**Comment by liamoreilly** [comment]
Having a single oauth2 provider works perfectly for me. So this should be great. I will work on this in the next week or so. Thanks!!
